import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-12">
      <Link href="/" className="mb-8 inline-block text-sm text-[var(--muted)] hover:text-[var(--gold)]">
        ← Back
      </Link>
      <h1 className="font-display text-3xl font-bold text-[var(--gold)]">
        Terms & Conditions
      </h1>
      <p className="mt-2 text-sm text-[var(--muted)]">Last updated: February 2026</p>

      <div className="mt-8 space-y-6 text-sm leading-relaxed text-[var(--muted)]">
        <section>
          <h2 className="mb-2 text-lg font-semibold text-[var(--light)]">1. About Athro Goals</h2>
          <p>
            Athro Goals (&quot;the Service&quot;) is operated by Athro AI Ltd, registered in Wales, United Kingdom. The Service provides AI-powered life-goal pathway generation — step-by-step plans with real dates and costs.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-[var(--light)]">2. Acceptance of Terms</h2>
          <p>
            By creating an account or using the Service, you agree to these Terms & Conditions. If you do not agree, do not use the Service.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-[var(--light)]">3. The Service</h2>
          <p>
            Athro Goals provides AI-generated life-goal pathways, including timelines, costs, and steps. This information is generated by artificial intelligence and should be treated as guidance only. We do not guarantee the accuracy, completeness, or currency of any information provided.
          </p>
          <p className="mt-2">
            You should always verify important decisions (such as financial commitments, deadlines, and eligibility) with relevant institutions and qualified advisors.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-[var(--light)]">4. Accounts</h2>
          <p>
            You must provide a valid email address to create an account. You are responsible for maintaining the security of your account credentials. You must be at least 13 years old to use the Service, or have parental/guardian consent.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-[var(--light)]">5. Subscriptions & Payments</h2>
          <p>
            Free accounts include limited pathway generations per month. Paid subscriptions (Explorer, Pro, Adviser) provide additional features and higher limits. Payments are processed securely via Stripe. Subscriptions renew automatically unless cancelled. You can cancel at any time through the billing portal in Settings.
          </p>
          <p className="mt-2">
            Refunds are handled on a case-by-case basis. Contact support for refund requests.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-[var(--light)]">6. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul className="mt-1 list-disc pl-5 space-y-1">
            <li>Use the Service for any unlawful purpose</li>
            <li>Attempt to reverse-engineer, copy, or redistribute the Service</li>
            <li>Use automated tools to scrape or bulk-access the Service</li>
            <li>Share account credentials with others</li>
            <li>Submit false or misleading information</li>
          </ul>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-[var(--light)]">7. Intellectual Property</h2>
          <p>
            The Service, including its design, code, AI models, and branding, is owned by Athro AI Ltd. Pathways generated for you are yours to use personally, but the underlying technology remains our property.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-[var(--light)]">8. Limitation of Liability</h2>
          <p>
            The Service is provided &quot;as is&quot; without warranties of any kind. Athro AI Ltd is not liable for any decisions you make based on AI-generated guidance. Our total liability is limited to the amount you have paid for the Service in the 12 months preceding any claim.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-[var(--light)]">9. Account Deletion</h2>
          <p>
            You may delete your account at any time through Settings. This will permanently remove all your data, including pathways and conversations. This action cannot be undone. You may download your data before deletion.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-[var(--light)]">10. Changes to Terms</h2>
          <p>
            We may update these terms from time to time. We will notify registered users of material changes by email. Continued use of the Service after changes constitutes acceptance of the new terms.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-[var(--light)]">11. Contact</h2>
          <p>
            For questions about these terms, contact us at{" "}
            <a href="mailto:support@athrogoals.co.uk" className="text-[var(--gold)] hover:underline">
              support@athrogoals.co.uk
            </a>
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-[var(--light)]">12. Governing Law</h2>
          <p>
            These terms are governed by the laws of England and Wales. Any disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales.
          </p>
        </section>
      </div>
    </div>
  );
}
