/**
 * Ingested gov.uk finance chunks — generated by scripts/ingest-govuk.ts
 * Run `npx tsx scripts/ingest-govuk.ts` to refresh.
 * Source: gov.uk Content API (trusted, official).
 */

export interface IngestedChunk {
  content: string;
  source: string;
  sourceUrl: string;
  fetchedAt: string;
}

export const INGESTED_GOVUK_CHUNKS: IngestedChunk[] = [
  {
    "content": "Buying a home takes about 5 months on average. The process can take longer if you’re part of a chain of buyers and sellers. If you’re also selling a home, read the guide to selling your home . This guide is for England and Wales. There are different rules for buying a home in Scotland and buying a home in Northern Ireland . To buy a home, you’ll need to: decide how much you need to borrow - you",
    "source": "gov.uk — Buying a home",
    "sourceUrl": "https://www.gov.uk/buying-a-home",
    "fetchedAt": "2026-02-26T00:59:26.434Z"
  },
  {
    "content": "need to: decide how much you need to borrow - you may be able to get financial help from the government through an affordable home ownership scheme choose a mortgage lender choose a property make an offer on a property exchange contracts - if the seller accepts your offer, they’re responsible for drawing up a legal contract to transfer ownership pay tax arrange and pay for searches and surveys",
    "source": "gov.uk — Buying a home",
    "sourceUrl": "https://www.gov.uk/buying-a-home",
    "fetchedAt": "2026-02-26T00:59:26.434Z"
  },
  {
    "content": "p pay tax arrange and pay for searches and surveys arrange for a removals company to help you move home An offer is not legally binding until contracts are exchanged. You may be able to get financial help from the government through an affordable home ownership scheme . If you’re buying property with someone else You can own a home with up to 3 other people. Find out more about the different types",
    "source": "gov.uk — Buying a home",
    "sourceUrl": "https://www.gov.uk/buying-a-home",
    "fetchedAt": "2026-02-26T00:59:26.434Z"
  },
  {
    "content": "er people. Find out more about the different types of joint property ownership . Protecting yourself from fraud There’s a risk of fraud when buying a home as this involves transferring large sums of money. It’s important to check that you: are speaking to or emailing the person or business you think it is transfer money to the correct bank account/s do not reveal too much personal information on",
    "source": "gov.uk — Buying a home",
    "sourceUrl": "https://www.gov.uk/buying-a-home",
    "fetchedAt": "2026-02-26T00:59:26.434Z"
  },
  {
    "content": "t/s do not reveal too much personal information on social media You can also speak to a legal professional for help and advice about property fraud. When you decide you want to buy a home, you may need to get a mortgage to buy it. If so, you need to work out how much you can afford to borrow. When deciding how much to lend you, a mortgage lender will consider: the total amount you can borrow",
    "source": "gov.uk — Buying a home",
    "sourceUrl": "https://www.gov.uk/buying-a-home",
    "fetchedAt": "2026-02-26T00:59:26.434Z"
  },
  {
    "content": "der will consider: the total amount you can borrow whether a deposit is needed how affordable your monthly mortgage payments will be How your mortgage affordability will be worked out The mortgage affordability assessment will take into account: your income your current outgoings, for example, utility bills, insurance and Council Tax It will also consider any changes that might affect whether you",
    "source": "gov.uk — Buying a home",
    "sourceUrl": "https://www.gov.uk/buying-a-home",
    "fetchedAt": "2026-02-26T00:59:26.434Z"
  },
  {
    "content": "consider any changes that might affect whether you would be able to afford repayments (for example if interest rates change, or if you were made redundant). Work out how much you can afford for a mortgage on the MoneyHelper website . Additional costs Other costs you may need to consider when buying a home include: taxes, like Stamp Duty Land Tax ( SDLT ), also called stamp duty surveys - read",
    "source": "gov.uk — Buying a home",
    "sourceUrl": "https://www.gov.uk/buying-a-home",
    "fetchedAt": "2026-02-26T00:59:26.434Z"
  },
  {
    "content": "ax ( SDLT ), also called stamp duty surveys - read about the different types of surveys you can have on a new home solicitor’s fees mortgage fees search fees land registration fees Property running costs There will be extra costs to run your home when you buy it. For example: Council Tax cost of heating the property other bills such as water and broadband If you’re buying a leasehold property You",
    "source": "gov.uk — Buying a home",
    "sourceUrl": "https://www.gov.uk/buying-a-home",
    "fetchedAt": "2026-02-26T00:59:26.434Z"
  },
  {
    "content": "roadband If you’re buying a leasehold property You may also have to pay: services charges (this usually covers building insurance) ground rent Find out leasehold service charges and expenses . Credit score Your credit score can affect whether you can get a mortgage and the kinds of deals you’ll be offered. The higher the number in your score, the more likely you are to be offered a mortgage. Find",
    "source": "gov.uk — Buying a home",
    "sourceUrl": "https://www.gov.uk/buying-a-home",
    "fetchedAt": "2026-02-26T00:59:26.434Z"
  },
  {
    "content": "more likely you are to be offered a mortgage. Find more information about how to check or improve your credit score on the MoneyHelper website . Identity checks You’ll need to prove your identity to your: estate agent solicitor mortgage lender Find more information about documents you need to have to prove your identity on the MoneyHelper website . There are different ways to own a property.",
    "source": "gov.uk — Buying a home",
    "sourceUrl": "https://www.gov.uk/buying-a-home",
    "fetchedAt": "2026-02-26T00:59:26.434Z"
  },
  {
    "content": "site . There are different ways to own a property. Leasehold and freehold properties If you’re buying a home, you can choose between: a leasehold property a freehold property If you buy a freehold property, you own the house and the land it’s built on. There are no leases and you do not have to pay ground rent or any maintenance fees. You’re responsible for maintaining your property and land, so",
    "source": "gov.uk — Buying a home",
    "sourceUrl": "https://www.gov.uk/buying-a-home",
    "fetchedAt": "2026-02-26T00:59:26.434Z"
  },
  {
    "content": "onsible for maintaining your property and land, so you’ll need to budget for these costs. Read more about leasehold and freehold properties on the MoneyHelper website . Energy Performance Certificate If you’re thinking of buying a property, the seller must have a valid Energy Performance Certificate ( EPC ) . This tells you the energy efficiency rating of a property. Before you make an offer,",
    "source": "gov.uk — Buying a home",
    "sourceUrl": "https://www.gov.uk/buying-a-home",
    "fetchedAt": "2026-02-26T00:59:26.434Z"
  },
  {
    "content": "cy rating of a property. Before you make an offer, check: what the property is worth the number of years on the lease (if relevant) what’s included in the sale what will be fixed or inspected before completion (boiler service for example) Make an offer on a property Once you’ve decided on a property, you can make an offer, usually through an estate agent. An offer is not legally binding in England",
    "source": "gov.uk — Buying a home",
    "sourceUrl": "https://www.gov.uk/buying-a-home",
    "fetchedAt": "2026-02-26T00:59:26.434Z"
  },
  {
    "content": "agent. An offer is not legally binding in England and Wales until you exchange contracts . If you make an offer ‘subject to contract’, this means the price can still be negotiated (for example, if a survey finds a problem with the property). Get a legal professional You’ll need to find a legal professional to handle the legal work involved in buying a home. This could be a: solicitor licensed",
    "source": "gov.uk — Buying a home",
    "sourceUrl": "https://www.gov.uk/buying-a-home",
    "fetchedAt": "2026-02-26T00:59:26.434Z"
  },
  {
    "content": "buying a home. This could be a: solicitor licensed conveyancer chartered legal executive Chartered Institute of Legal Executives ( CILEX ) practitioner Read more about how to buy and sell a home through estate agents on the MoneyHelper website . Searches and valuation Once your offer has been accepted, your solicitor or conveyancer will organise local authority searches on the property. This",
    "source": "gov.uk — Buying a home",
    "sourceUrl": "https://www.gov.uk/buying-a-home",
    "fetchedAt": "2026-02-26T00:59:26.434Z"
  },
  {
    "content": "ise local authority searches on the property. This usually includes a: local authority search water and drainage search environmental search You usually have to pay for the searches up front. Your mortgage provider will carry out a valuation of the property before they approve your mortgage. Surveys You can get a homebuyer survey to check the condition of the property. Read more about the",
    "source": "gov.uk — Buying a home",
    "sourceUrl": "https://www.gov.uk/buying-a-home",
    "fetchedAt": "2026-02-26T00:59:26.434Z"
  },
  {
    "content": "the condition of the property. Read more about the different types of surveys you can get on the MoneyHelper website . Recommendations from estate agents or mortgage lenders Some estate agents and mortgage lenders might recommend legal professionals, mortgage brokers or surveyors to you. You must be told if the estate agent or mortgage lender gets a payment (a ‘referral fee’) from the company",
    "source": "gov.uk — Buying a home",
    "sourceUrl": "https://www.gov.uk/buying-a-home",
    "fetchedAt": "2026-02-26T00:59:26.434Z"
  },
  {
    "content": "gets a payment (a ‘referral fee’) from the company they’re recommending. You do not have to use the company that’s been recommended to you. Once the offer is accepted, the seller is responsible for drawing up a legal contract to transfer ownership. The contract contains details about: the sale price the property boundaries which fixtures and fittings (like carpets and kitchen units) are included",
    "source": "gov.uk — Buying a home",
    "sourceUrl": "https://www.gov.uk/buying-a-home",
    "fetchedAt": "2026-02-26T00:59:26.434Z"
  },
  {
    "content": "ings (like carpets and kitchen units) are included any legal restrictions or rights, like public footpaths or rules about using the property any planning restrictions services to the property, like drainage and gas when the sale will complete If the seller has hired a solicitor or conveyancer, they will: draft the initial contract answer questions from your solicitor or conveyancer (with the",
    "source": "gov.uk — Buying a home",
    "sourceUrl": "https://www.gov.uk/buying-a-home",
    "fetchedAt": "2026-02-26T00:59:26.434Z"
  },
  {
    "content": "tions from your solicitor or conveyancer (with the seller’s help) negotiate the details of the contract if necessary Exchanging contracts When you (the buyer) and seller are happy with the contract, both sides sign final copies and send them to each other. The agreement to sell and buy is legally binding once this happens. Usually neither of you can pull out without paying compensation. Completion",
    "source": "gov.uk — Buying a home",
    "sourceUrl": "https://www.gov.uk/buying-a-home",
    "fetchedAt": "2026-02-26T00:59:26.434Z"
  },
  {
    "content": "n pull out without paying compensation. Completion Once you exchange contracts and the seller deals with any remaining checks you’ve asked for: Your solicitor or conveyancer will transfer your money to the seller. You’ll be sent the legal documents needed to transfer ownership. The seller moves out and leaves the property in the state agreed in the contract. You get the keys to the property from",
    "source": "gov.uk — Buying a home",
    "sourceUrl": "https://www.gov.uk/buying-a-home",
    "fetchedAt": "2026-02-26T00:59:26.434Z"
  },
  {
    "content": "he contract. You get the keys to the property from the seller or estate agent. You now own the property. You may need to pay: Stamp Duty Land Tax ( SDLT ) when you buy a home in England and Northern Ireland Land Transaction Tax when you buy a home in Wales Stamp Duty Land Tax You pay SDLT if the property is worth £250,000 or more. If you’re buying your first home, you do not have to pay SDLT if",
    "source": "gov.uk — Buying a home",
    "sourceUrl": "https://www.gov.uk/buying-a-home",
    "fetchedAt": "2026-02-26T00:59:26.434Z"
  },
  {
    "content": "ng your first home, you do not have to pay SDLT if the property is £425,000 or less. There were different thresholds and rates for residential properties before 23 September 2022 . You can make a complaint to a company involved in the sale if you’re unhappy with their service. Follow the company’s complaints procedure. If they do not respond or you’re not happy with their response, you can",
    "source": "gov.uk — Buying a home",
    "sourceUrl": "https://www.gov.uk/buying-a-home",
    "fetchedAt": "2026-02-26T00:59:26.434Z"
  },
  {
    "content": "d or you’re not happy with their response, you can complain to the relevant ombudsman service or scheme. That ombudsman will investigate the complaint for free. Complain about an estate agent You can complain to one of the following: The Property Ombudsman Property Redress Scheme Ask the estate agent which scheme they belong to. The Which? website has more advice on how to make a complaint about",
    "source": "gov.uk — Buying a home",
    "sourceUrl": "https://www.gov.uk/buying-a-home",
    "fetchedAt": "2026-02-26T00:59:26.434Z"
  },
  {
    "content": "e has more advice on how to make a complaint about an estate agent. Complain about a legal professional Contact the Legal Ombudsman . Citizens Advice has more advice on how to make a complaint about a solicitor or conveyancer. Complain about a mortgage lender Contact the Financial Ombudsman Service . Complain about a valuer or surveyor Contact the Royal Institution of Chartered Surveyors if the",
    "source": "gov.uk — Buying a home",
    "sourceUrl": "https://www.gov.uk/buying-a-home",
    "fetchedAt": "2026-02-26T00:59:26.434Z"
  },
  {
    "content": "he Royal Institution of Chartered Surveyors if the valuer or surveyor is a member. Citizens Advice has advice on how to complain about a surveyor. Complain about a new home Contact the New Homes Ombudsman Service",
    "source": "gov.uk — Buying a home",
    "sourceUrl": "https://www.gov.uk/buying-a-home",
    "fetchedAt": "2026-02-26T00:59:26.434Z"
  },
  {
    "content": "You can use a Lifetime ISA (Individual Savings Account) to buy your first home or save for later life. You can put in up to £4,000 each year, until you’re 50. You must make your first payment into your ISA before you’re 40. The government will add a 25% bonus to your savings, up to a maximum of £1,000 per year. The Lifetime ISA limit of £4,000 counts towards your annual ISA limit . This is £20,000",
    "source": "gov.uk — Lifetime ISA",
    "sourceUrl": "https://www.gov.uk/lifetime-isa",
    "fetchedAt": "2026-02-26T00:59:26.484Z"
  },
  {
    "content": "ts towards your annual ISA limit . This is £20,000 for the 2025 to 2026 tax year. You can hold cash or stocks and shares in your Lifetime ISA or have a combination of both. When you turn 50, you will not be able to pay into your Lifetime ISA or earn the 25% bonus. Your account will stay open and your savings will still earn interest or investment returns. You must be 18 or over but under 40 to",
    "source": "gov.uk — Lifetime ISA",
    "sourceUrl": "https://www.gov.uk/lifetime-isa",
    "fetchedAt": "2026-02-26T00:59:26.484Z"
  },
  {
    "content": "nt returns. You must be 18 or over but under 40 to open a Lifetime ISA . To open and continue to pay into a Lifetime ISA you must also be either: resident in the UK a member of the armed forces or a crown servant (for example diplomatic or overseas Civil Service) or their spouse or civil partner if you do not live in the UK You can work out your residence status if you’re unsure - read UK",
    "source": "gov.uk — Lifetime ISA",
    "sourceUrl": "https://www.gov.uk/lifetime-isa",
    "fetchedAt": "2026-02-26T00:59:26.484Z"
  },
  {
    "content": "t your residence status if you’re unsure - read UK residence and tax for more details. You can withdraw money from your ISA if you’re: buying your first home aged 60 or over terminally ill, with less than 12 months to live You’ll pay a withdrawal charge of 25% if you withdraw cash or assets for any other reason (also known as making an unauthorised withdrawal). Buying your first home You can use",
    "source": "gov.uk — Lifetime ISA",
    "sourceUrl": "https://www.gov.uk/lifetime-isa",
    "fetchedAt": "2026-02-26T00:59:26.484Z"
  },
  {
    "content": "ed withdrawal). Buying your first home You can use your savings to help you buy your first home if all the following apply: the property costs £450,000 or less you buy the property at least 12 months after you make your first payment into the Lifetime ISA you use a conveyancer or solicitor to act for you in the purchase - the ISA provider will pay the funds directly to them you’re buying with a",
    "source": "gov.uk — Lifetime ISA",
    "sourceUrl": "https://www.gov.uk/lifetime-isa",
    "fetchedAt": "2026-02-26T00:59:26.484Z"
  },
  {
    "content": "ay the funds directly to them you’re buying with a mortgage You cannot use your savings to buy a home if you’re getting a private mortgage from: your relative (a parent, grandparent, child, grandchild or sibling) someone who is married or in a civil partnership with your relative your spouse or civil partner a relative of your spouse or civil partner someone who is married or in a civil",
    "source": "gov.uk — Lifetime ISA",
    "sourceUrl": "https://www.gov.uk/lifetime-isa",
    "fetchedAt": "2026-02-26T00:59:26.484Z"
  },
  {
    "content": "civil partner someone who is married or in a civil partnership with a relative of your spouse or civil partner Buying with someone else If the person you’re buying with has a Lifetime ISA , you can both use your savings and government bonus. To qualify you must both: be first-time buyers meet all the conditions under ‘Buying your first home’ If you have a Help to Buy ISA If you have a Help to Buy",
    "source": "gov.uk — Lifetime ISA",
    "sourceUrl": "https://www.gov.uk/lifetime-isa",
    "fetchedAt": "2026-02-26T00:59:26.484Z"
  },
  {
    "content": "u have a Help to Buy ISA If you have a Help to Buy ISA as well as a Lifetime ISA , you can only use the government bonus from one of them to buy your first home. You can transfer money from a Help to Buy ISA to a Lifetime ISA . If you transfer money from a Lifetime ISA to a Help to Buy ISA you’ll have to pay the 25% withdrawal charge. Saving for later life You can take your savings out of a",
    "source": "gov.uk — Lifetime ISA",
    "sourceUrl": "https://www.gov.uk/lifetime-isa",
    "fetchedAt": "2026-02-26T00:59:26.484Z"
  },
  {
    "content": "for later life You can take your savings out of a Lifetime ISA when you’re 60 or over. You’ll pay a 25% charge if you withdraw money or transfer the Lifetime ISA to another type of ISA before 60. If you die your Lifetime ISA ends on the date of your death. There’s no charge to withdraw the funds or assets from your account. A Lifetime ISA is one of a number of ways to save for later life . If you",
    "source": "gov.uk — Lifetime ISA",
    "sourceUrl": "https://www.gov.uk/lifetime-isa",
    "fetchedAt": "2026-02-26T00:59:26.484Z"
  },
  {
    "content": "f a number of ways to save for later life . If you need to make an unauthorised withdrawal You’ll pay a withdrawal charge of 25%. This recovers the government bonus you received on your original savings. If you wish to withdraw the entire pot, a 25% charge will apply to the total amount in your ISA , including the government bonus. If you only wish to access some of your money, you’ll have to take",
    "source": "gov.uk — Lifetime ISA",
    "sourceUrl": "https://www.gov.uk/lifetime-isa",
    "fetchedAt": "2026-02-26T00:59:26.484Z"
  },
  {
    "content": "to access some of your money, you’ll have to take the withdrawal charge into account when requesting funds. You’ll have to withdraw more than the amount you need, to cover your needs and the 25% withdrawal charge. Example 1 Assuming no growth, initial savings of £800 will earn a 25% government bonus of £200 and give you a pot of £1,000. If you wish to withdraw the entire pot, a 25% charge will",
    "source": "gov.uk — Lifetime ISA",
    "sourceUrl": "https://www.gov.uk/lifetime-isa",
    "fetchedAt": "2026-02-26T00:59:26.484Z"
  },
  {
    "content": "wish to withdraw the entire pot, a 25% charge will apply to the full £1,000. You’ll have to pay a government withdrawal charge of £250. This will leave you with £750. Example 2 If you need enough cash to cover a £120 bill, you’ll have to withdraw more than you actually require. Withdrawing £160 means you pay a 25% withdrawal charge of £40 and receive £120 in cash to meet the bill.",
    "source": "gov.uk — Lifetime ISA",
    "sourceUrl": "https://www.gov.uk/lifetime-isa",
    "fetchedAt": "2026-02-26T00:59:26.484Z"
  },
  {
    "content": "You must pay Stamp Duty Land Tax ( SDLT ) if you buy a property or land over a certain price in England and Northern Ireland. The tax is different if the property or land is in: Scotland - pay Land and Buildings Transaction Tax Wales - pay Land Transaction Tax if the sale was completed on or after 1 April 2018 You pay the tax when you: buy a freehold property buy a new or existing leasehold buy a",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "old property buy a new or existing leasehold buy a property through a shared ownership scheme are transferred land or property in exchange for payment, for example you take on a mortgage or buy a share in a house Thresholds The threshold is where SDLT starts to apply. If you buy a property for less than the threshold, there’s no SDLT to pay. SDLT starts to apply when you buy property that costs:",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "starts to apply when you buy property that costs: £125,000 for residential properties £300,000 for first-time buyers buying a residential property worth £500,000 or less £150,000 for non-residential land and properties Find out more about previous SDLT thresholds and rates for residential properties . How much you pay How much you pay depends on: whether the land or property will be used as a",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "on: whether the land or property will be used as a residential property or as a non-residential or mixed-use property whether you are eligible for relief or an exemption For example, if you’re buying a residential property there are different rates of SDLT if: you’re a first-time buyer you already own a property and you’re buying an additional property you’re not a UK resident You can use HM",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "l property you’re not a UK resident You can use HM Revenue and Customs’ ( HMRC ) Stamp Duty Land Tax calculator to work out how much tax you’ll pay. The value you pay SDLT on (the ‘consideration’) The total value you pay SDLT on (sometimes called the ‘consideration’) is usually the price you pay for the property or land. Sometimes it might include another type of payment like: goods works or",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "clude another type of payment like: goods works or services release from a debt transfer of a debt, including the value of any outstanding mortgage Find out how to work out the consideration if your situation is complicated. How and when to pay Send an SDLT return to HMRC and pay the tax within 14 days of completion . If you have a solicitor, agent or conveyancer, they’ll usually file your return",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "t or conveyancer, they’ll usually file your return and pay the tax on your behalf on the day of completion. They’ll then add the tax to their fees. If they do not do this for you, you can file a return and pay the tax yourself. You may be charged penalties and interest if you do not file your return and make your payment within 14 days of completion. You usually pay Stamp Duty Land Tax ( SDLT ) on",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "n. You usually pay Stamp Duty Land Tax ( SDLT ) on increasing portions of the property price when you buy residential property, for example a house or flat. The amount you pay depends on: when you bought the property how much you paid for it whether you’re eligible for relief or an exemption Use the SDLT calculator to work out how much tax you’ll pay. Find out more about previous SDLT thresholds",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "pay. Find out more about previous SDLT thresholds and rates for residential properties . Rates for a single property You pay SDLT at these rates if, after buying the property, it is the only residential property you own. You usually pay 5% on top of these rates if you own another residential property. Property or lease premium or transfer value SDLT rate Up to £125,000 Zero The next £125,000 (the",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "LT rate Up to £125,000 Zero The next £125,000 (the portion from £125,001 to £250,000) 2% The next £675,000 (the portion from £250,001 to £925,000) 5% The next £575,000 (the portion from £925,001 to £1.5 million) 10% The remaining amount (the portion above £1.5 million) 12% Example In April 2025 you buy a house for £295,000. The SDLT you owe will be calculated as follows: 0% on the first £125,000 =",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "calculated as follows: 0% on the first £125,000 = £0 2% on the second £125,000 = £2,500 5% on the final £45,000 = £2,250 total SDLT = £4,750 Use the SDLT calculator to work out how much tax you’ll pay. New leasehold sales and transfers When you buy a new residential leasehold property you pay SDLT on the purchase price of the lease (the ‘lease premium’) using the rates above. If the total rent",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "premium’) using the rates above. If the total rent over the life of the lease (known as the ‘net present value’) is more than the SDLT threshold (currently £125,000), you’ll pay SDLT at 1% on the portion over £125,000. This does not apply to existing (‘assigned’) leases. You can work out how much SDLT you’ll pay for your residential lease using HMRC ’s: SDLT calculator guidance on leasehold",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "ing HMRC ’s: SDLT calculator guidance on leasehold purchases If you’re buying your first home You can claim a discount (relief) if the property you buy is your first home. You’re eligible if you and anyone else you’re buying with are first-time buyers. You’ll pay: no SDLT up to £300,000 5% SDLT on the portion from £300,001 to £500,000 If the price is over £500,000, you cannot claim the relief.",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "ice is over £500,000, you cannot claim the relief. Follow the rules for people who’ve bought a home before. Example You are a first-time buyer and purchase a property for £500,000. The SDLT you owe will be calculated as: 0% on the first £300,000 = £0 5% on the remaining £200,000 = £10,000 total SDLT = £10,000 Higher rates for additional properties You’ll usually have to pay 5% on top of SDLT rates",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "You’ll usually have to pay 5% on top of SDLT rates if buying a new residential property means you’ll own more than one. Use the SDLT calculator or check the higher rates to work out how much tax you’ll pay. If you’re replacing your main residence You will not pay the extra 5% SDLT if both of the following apply: the property you’re buying is replacing your main residence your previous main",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "s replacing your main residence your previous main residence was sold within 36 months of completing your new purchase If you have not sold your main residence on the day you complete your new purchase, you’ll have to pay higher rates. This is because you own 2 properties. Check if you’re eligible for a refund of the higher rates of SDLT . Rates if you’re not a UK resident If you’re not present in",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "you’re not a UK resident If you’re not present in the UK for at least 183 days (6 months) during the 12 months before your purchase you are ‘not a UK resident’ for the purposes of SDLT . You’ll usually pay a 2% surcharge if you’re buying a residential property in England or Northern Ireland. You may not have to pay a surcharge on certain properties, transactions or if you’re a particular type of",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "es, transactions or if you’re a particular type of buyer. Check if you’re eligible for a refund of the surcharge. If you have to pay the surcharge, you’ll also have to pay any other rates of SDLT that apply, for example: if you already own a property and you’re buying an additional property if you’re a first-time buyer Use the SDLT calculator to work out how much tax you’ll pay. Special rates",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "to work out how much tax you’ll pay. Special rates There are different SDLT rules and rate calculations for: corporate bodies people buying 6 or more residential properties in one transaction shared ownership properties multiple purchases or transfers between the same buyer and seller (‘linked purchases’) companies and trusts buying residential property You pay Stamp Duty Land Tax ( SDLT ) on",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "l property You pay Stamp Duty Land Tax ( SDLT ) on increasing portions of the property price (or ‘consideration’) when you pay £150,000 or more for non-residential or mixed (also known as ‘mixed use’) land or property. You must still send an SDLT return for most transactions under £150,000. Non-residential property includes: commercial property, for example shops or offices property that is not",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "for example shops or offices property that is not suitable to be lived in and cannot be made suitable (for example, there is a high risk of structural collapse or the property is radioactive) forests agricultural land that’s part of a working farm or used for agricultural reasons any other land or property that is not part of a dwelling’s garden or grounds 6 or more residential properties bought",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "or grounds 6 or more residential properties bought in a single transaction You pay residential SDLT rates on agricultural land if it’s sold as part of the garden or grounds of a dwelling, for example a cottage with fields. A ‘mixed’ property is one that has both residential and non-residential elements, for example a flat connected to a shop, doctor’s surgery or office. Use the SDLT calculator to",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "or’s surgery or office. Use the SDLT calculator to work out how much tax you’ll pay. Freehold sales and transfers You can also use this table to work out the SDLT rate for a lease premium. Property or lease premium or transfer value SDLT rate Up to £150,000 Zero The next £100,000 (the portion from £150,001 to £250,000) 2% The remaining amount (the portion above £250,000) 5% Example If you buy a",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "he portion above £250,000) 5% Example If you buy a freehold commercial property for £275,000, the SDLT you owe is calculated as follows: 0% on the first £150,000 = £0 2% on the next £100,000 = £2,000 5% on the final £25,000 = £1,250 Total SDLT = £3,250 New leasehold sales and transfers When you buy a new non-residential or mixed leasehold you pay SDLT on both the: purchase price of the lease (the",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "SDLT on both the: purchase price of the lease (the ‘lease premium’) using the rates above value of the annual rent you pay (the ‘net present value’) These are calculated separately then added together. If you buy an existing (‘assigned’) lease , you only pay SDLT on the lease price (or ‘consideration’) . The net present value (NPV) is based on the total rent over the life of the lease. You do not",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "total rent over the life of the lease. You do not pay SDLT on the rent if the NPV is less than £150,000. Net present value of rent SDLT rate £0 to £150,000 Zero The portion from £150,001 to £5,000,000 1% The portion above £5,000,000 2% How much you’ll pay You can work out how much SDLT you’ll pay for your non-residential lease using HM Revenue and Customs’ ( HMRC ): SDLT calculator guidance on",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "and Customs’ ( HMRC ): SDLT calculator guidance on buying leasehold properties You may pay a higher rate of SDLT for multiple purchases or transfers from the same seller. You may have to pay Stamp Duty Land Tax ( SDLT ) if the ownership of land or property is transferred to you in exchange for any payment (or ‘consideration’) . The rules around SDLT depend on the specific circumstances surrounding",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "T depend on the specific circumstances surrounding the transfer. HM Revenue and Customs ( HMRC ) has guidance on transfers : as a result of marriage, civil partnerships or moving in together on divorce, separation or the end of a civil partnership of jointly owned property or land if the larger share is given as a gift given as a gift or left in a will to or from a company You may have to pay",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "in a will to or from a company You may have to pay Stamp Duty Land Tax ( SDLT ) when you buy a property through a shared ownership scheme run by an approved public body. This includes: local housing authorities housing associations housing action trusts the Northern Ireland Housing Executive the Commission for the New Towns development corporations You can choose to either: make a one-off payment",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "s You can choose to either: make a one-off payment based on the market value of the property (‘market value election’) pay SDLT in stages If you’re a first-time buyer and buying your first share, you may be able to reduce the amount of tax you pay by claiming relief . Market value election Submit a return and pay SDLT at the residential rate . Use the total market value of the property to",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "te . Use the total market value of the property to calculate how much to pay - even if you’re only buying a share. You do not pay any more SDLT after this, even if you buy a bigger share in the property later on. Example You pay £140,000 to buy a 50% share of a property with a market value of £280,000. The SDLT you pay will be calculated as follows: 0% on the first £125,000 = £0 2% on the second",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "ws: 0% on the first £125,000 = £0 2% on the second £125,000 = £2,500 5% on the final £30,000 = £1,500 total SDLT = £4,000 HM Revenue and Customs (HMRC) has guidance on how much SDLT you’ll pay if you do not have the right to the freehold. Paying in stages You make your first SDLT payment on the price you pay for the lease (the ‘lease premium’) if it’s above the SDLT threshold for residential rates",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "t’s above the SDLT threshold for residential rates . If the lease premium is below the threshold, you do not pay SDLT at this point - but you still have to submit a return. You may have to pay extra SDLT if the total rent over the life of the lease (known as the ‘net present value’) is more than the SDLT threshold . Work this out on HMRC’s SDLT calculator . You pay SDLT of 1% on the amount over",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "calculator . You pay SDLT of 1% on the amount over the threshold - add this to any SDLT you’re paying on the lease premium. SDLT if you buy more shares If you buy any more shares in the property, you do not have to pay any more SDLT or send a return to HMRC until you own more than an 80% share. Once your share of the property goes over 80% you must send a return and pay SDLT on: the transaction",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "ust send a return and pay SDLT on: the transaction that took you over 80% any transactions after that Calculating your SDLT To work out the SDLT if you buy more shares that take you over 80%: Work out the SDLT due on the total you’ve paid for the property to date - include any amounts you did not pay tax on. Use the residential rate that applies at the time you bought the new share. For example,",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "at the time you bought the new share. For example, if you’ve paid £260,000 in total so far, the total SDLT due is £3,000 (0% on the first £125,000, 2% on the second £125,000 and 5% on the final £10,000). Divide the amount you’re paying for this share by the total amount you’ve paid for the property to date. For example, if you’re paying £65,000 for this share, divide £65,000 by £260,000 = 0.25.",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "for this share, divide £65,000 by £260,000 = 0.25. Multiply the two figures, for example SDLT of £3000 multiplied by 0.25 = £750. This is the amount you would need to pay in SDLT for this share. Additional tax if payments are linked You may have to pay extra SDLT on previous shares if they become ‘linked’ to later shares. Shares only become linked once you own over 80% of the property. You can",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "ked once you own over 80% of the property. You can read more about how much SDLT you’ll pay when you buy more shares. You may be eligible for Stamp Duty Land Tax ( SDLT ) reliefs if you’re buying your first home and in certain other situations. These reliefs can reduce the amount of tax you pay. You must complete an SDLT return to claim relief, even if no tax is due. HM Revenue and Customs ( HMRC",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "en if no tax is due. HM Revenue and Customs ( HMRC ) has guidance on SDLT reliefs for: first-time buyers building companies buying an individual’s home employers buying an employee’s house local councils making compulsory purchases property developers providing amenities to communities companies transferring property to another company charities buying for charitable purposes right to buy",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "rities buying for charitable purposes right to buy properties registered providers of social housing Crown employees property investment funds, for example Property Authorised Investment Funds (PAIFs) and Co-ownership Authorised Contractual Schemes (CoACSs) You can no longer claim SDLT relief for multiple dwellings. You can also read guidance on freeport tax sites . Exemptions You do not have to",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "freeport tax sites . Exemptions You do not have to pay SDLT or file a return if: no money or other payment changes hands for a land or property transfer property is left to you in a will property is transferred because of divorce or dissolution of a civil partnership you buy a freehold property for less than £40,000 you buy a new or assigned lease of 7 years or more, as long as the premium is less",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "of 7 years or more, as long as the premium is less than £40,000 and the annual rent is less than £1,000 you buy a new or assigned lease of less than 7 years, as long as the amount you pay is less than the residential threshold or non-residential threshold of SDLT you use alternative property financial arrangements, for example to comply with Sharia law, where the alternative financial provider",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "aria law, where the alternative financial provider pays SDLT when they buy the property under the arrangements Read HMRC ’s guidance on transactions that do not need a return . You may be able to get a refund of Stamp Duty Land Tax ( SDLT ) if, for example: you paid the higher rates of SDLT on the purchase of a new main home but you’ve sold your previous main home you were not resident in the UK",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "previous main home you were not resident in the UK and paid a surcharge to purchase residential property in England or Northern Ireland but are now ‘a UK resident’ for the purposes of SDLT you’re eligible for a relief or exemption which you did not claim in your original SDLT return you paid the residential property rates of SDLT but you should have paid the non-residential rates you made a",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "uld have paid the non-residential rates you made a mistake in calculating the amount of SDLT due on your original SDLT return, meaning you have overpaid you calculated the correct amount of SDLT on your return, but have paid too much to HM Revenue and Customs ( HMRC ) in error How to claim a refund You must include all purchasers on the claim if there’s more than one. If you paid an agent to claim",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "ere’s more than one. If you paid an agent to claim for you, you are still responsible for checking whether your claim is correct. You will still have to repay the refund in full, along with any interest or penalties due, if the claim your agent made is wrong. How you claim depends on your circumstances. Use this tool to check how to claim a refund. Check now How you will get your refund HMRC will",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": ". Check now How you will get your refund HMRC will usually make the payment directly into your bank account within 15 working days of receiving your claim. HMRC may contact you by post if they need further information. After paying a refund, HMRC may find that your claim is wrong. If that happens, you must repay the refund in full along with any interest due. You may also be charged a penalty.",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "y interest due. You may also be charged a penalty. Read the Penalties section of the SDLT compliance checks guidance to find out how HMRC decide penalty amounts .",
    "source": "gov.uk — Stamp Duty Land Tax",
    "sourceUrl": "https://www.gov.uk/stamp-duty-land-tax",
    "fetchedAt": "2026-02-26T00:59:26.620Z"
  },
  {
    "content": "You may be able to get financial help from the government to buy a home. You could get: a home for less than its market value if you’re a first time buyer (in England) a home through shared ownership (UK wide) lower rent payments to help save for a deposit if you’re a tenant (in England) a loan to help with the cost of building a home or hiring someone to build one ( in Scotland and in Wales ) a",
    "source": "gov.uk — Affordable home ownership schemes",
    "sourceUrl": "https://www.gov.uk/affordable-home-ownership-schemes",
    "fetchedAt": "2026-02-26T00:59:26.740Z"
  },
  {
    "content": "omeone to build one ( in Scotland and in Wales ) a loan to help with the cost of a new-build home if you’re a first-time buyer (in Wales) You can no longer open a Help to Buy ISA . You can still open a Lifetime ISA to save for a first home. Buying your council or housing association property There are also schemes for council tenants and housing association tenants .",
    "source": "gov.uk — Affordable home ownership schemes",
    "sourceUrl": "https://www.gov.uk/affordable-home-ownership-schemes",
    "fetchedAt": "2026-02-26T00:59:26.740Z"
  }
];
