import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import prisma from "@/lib/prisma";
import { getOrCreateUser } from "@/lib/user";

export async function POST(req: NextRequest) {
  try {
    const supabase = await createClient();
    const {
      data: { user: authUser },
    } = await supabase.auth.getUser();
    if (!authUser) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const dbUser = await getOrCreateUser(authUser);
    const { pathwayId } = (await req.json()) as { pathwayId: string };

    const pathway = await prisma.pathway.findFirst({
      where: { id: pathwayId, userId: dbUser.id },
      include: { steps: { orderBy: { stepOrder: "asc" } } },
    });

    if (!pathway) {
      return NextResponse.json({ error: "Pathway not found" }, { status: 404 });
    }

    if (pathway.status !== "COMPLETE") {
      return NextResponse.json(
        { error: "Pathway must be complete to export" },
        { status: 400 }
      );
    }

    const data = pathway.pathwayData as Record<string, unknown> | null;
    const stepDataList = (data?.steps as Array<Record<string, unknown>>) ?? [];

    const lines: string[] = [];

    lines.push(`🎯 ${pathway.goal ?? "Pathway"}`);
    lines.push("");

    if (pathway.summaryText) {
      lines.push(pathway.summaryText);
      lines.push("");
    }

    if (pathway.estimatedYears != null) {
      lines.push(`⏱ ~${pathway.estimatedYears} years`);
    }
    if (pathway.estimatedTotalCost != null) {
      lines.push(`💰 £${pathway.estimatedTotalCost.toLocaleString()} estimated`);
    }
    const costContext = data?.costContext as string | undefined;
    if (costContext) {
      lines.push(costContext);
    }
    lines.push("");
    lines.push("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
    lines.push("");

    pathway.steps.forEach((step, i) => {
      const stepData = stepDataList[i] as Record<string, unknown> | undefined;
      const costNote = stepData?.costNote as string | undefined;

      lines.push(`Step ${step.stepOrder}: ${step.title}`);
      if (step.definiteDate) {
        lines.push(`📅 ${step.definiteDate}`);
      }
      if (step.stageLabel) {
        lines.push(`Stage: ${step.stageLabel}`);
      }
      if (step.timelineMonths != null) {
        lines.push(
          `Duration: ${step.timelineMonths >= 12 ? `${Math.round(step.timelineMonths / 12)} year(s)` : `${step.timelineMonths} months`}`
        );
      }
      lines.push("");
      lines.push(step.description);

      if (step.estimatedCost != null || costNote) {
        lines.push("");
        if (step.estimatedCost != null) {
          lines.push(`💰 Est. cost: £${step.estimatedCost.toLocaleString()}`);
        }
        if (costNote) {
          lines.push(costNote);
        }
      }

      if (step.tips) {
        lines.push("");
        lines.push(`💡 Tips: ${step.tips}`);
      }

      const checklist = step.checklist;
      const checklistArr = Array.isArray(checklist)
        ? checklist.filter((x): x is string => typeof x === "string")
        : [];
      if (checklistArr.length > 0) {
        lines.push("");
        lines.push("Checklist:");
        for (const item of checklistArr) {
          lines.push(`☐ ${item}`);
        }
      }

      const sources = step.sources as { names?: string[] } | string[] | null;
      const names = Array.isArray(sources) ? sources : sources?.names ?? [];
      if (names.length > 0) {
        lines.push(`Sources: ${names.join(", ")}`);
      }

      lines.push("");
      lines.push("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
      lines.push("");
    });

    lines.push("Generated by Athro Goals — athrogoals.co.uk");

    const text = lines.join("\n");
    const title = pathway.goal ?? "Pathway";

    return NextResponse.json({ text, title });
  } catch (error) {
    console.error("Export text error:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}
