#!/usr/bin/env npx tsx
/**
 * Ingest gov.uk finance content into RAG chunks.
 * Run: npx tsx scripts/ingest-govuk.ts
 * Output: src/lib/rag/ingestedChunks.ts
 */

import * as fs from "fs";
import * as path from "path";
import { ingestAllFinance } from "../src/lib/ingestion/govukIngestion";

async function main() {
  console.log("Ingesting gov.uk finance content...");
  const chunks = await ingestAllFinance();
  console.log(`Ingested ${chunks.length} chunks from gov.uk`);

  const outPath = path.join(
    process.cwd(),
    "src/lib/rag/ingestedChunks.ts"
  );

  const content = `/**
 * Ingested gov.uk finance chunks — generated by scripts/ingest-govuk.ts
 * Run \`npx tsx scripts/ingest-govuk.ts\` to refresh.
 * Source: gov.uk Content API (trusted, official).
 */

export interface IngestedChunk {
  content: string;
  source: string;
  sourceUrl: string;
  fetchedAt: string;
}

export const INGESTED_GOVUK_CHUNKS: IngestedChunk[] = ${JSON.stringify(chunks, null, 2)};
`;

  fs.writeFileSync(outPath, content, "utf-8");
  console.log(`Wrote ${chunks.length} chunks to ${outPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
